# This is a basic workflow to help you get started with Actions

name: CI build and deploy production

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
    paths:
      - "src/**"
      - "tailwind.config.js"
      - "tailwind.config.css"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Configure dist directory
        run: |
          mkdir -p dist
          cp -r ./src/* ./dist
          rm ./dist/tailwind.css

      - name: TailwindCSS dependencies
        run: npm install -D tailwindcss

      - name: Build production
        run: NODE_ENV=production npx tailwindcss -i tailwind.config.css -o ./dist/tailwind.css -c ./tailwind.config.js --minify

      - name: setup git config
        run: |
          git config user.name "Actions: Deploy Production Bot"
          git config user.email "<>"

      - name: Commit to production
        run: |
          git checkout --orphan production
          git add -A
          git commit -am "Production build `date`"
          git branch -D master
          git branch -m production
          git push -f origin production

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: dist
